import os


class Config:
    TESTIER_GITHUB_APP_ID = os.getenv("TESTIER_GITHUB_APP_ID")
    TESTIER_GITHUB_APP_PRIVATE_KEY = os.getenv("TESTIER_GITHUB_APP_PRIVATE_KEY")
    MAIN_BRANCH = os.getenv("TESTIER_MAIN_BRANCH", "main")
    DB_CONNECTION_STRING = os.getenv("TESTIER_DB_CONNECTION_STRING")
